// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUA52j_ymehKAy7IEdb5gqxJNFKbQZ_XY',
    appId: '1:959794755644:web:026e35a5def60b4878eb39',
    messagingSenderId: '959794755644',
    projectId: 'deuscurat-admin',
    authDomain: 'deuscurat-admin.firebaseapp.com',
    storageBucket: 'deuscurat-admin.appspot.com',
    measurementId: 'G-1NM9F07B3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxQCQEw6VHpTrUuO17SmGvcvsGYeH3vAA',
    appId: '1:959794755644:android:6c0426a85b73512778eb39',
    messagingSenderId: '959794755644',
    projectId: 'deuscurat-admin',
    storageBucket: 'deuscurat-admin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBfoShSgofjBzs5N0EGcAcOU9WeiXbOGY',
    appId: '1:959794755644:ios:7b6f2aa663004be378eb39',
    messagingSenderId: '959794755644',
    projectId: 'deuscurat-admin',
    storageBucket: 'deuscurat-admin.appspot.com',
    iosClientId: '959794755644-iepslacb1kjbsgbos5haftfin500a7va.apps.googleusercontent.com',
    iosBundleId: 'co.miriamly.deuscuratAdmin',
  );
}
